insert into CELULAR_INFO(ID_CELULAR_INFO,DS_MODELO,NR_MEMORIA,NR_CAMERA_TRASEIRA_MP,NR_TELA_TAMANHO,NR_PRECO,NR_CAMERA_FRONTAL_MP) 
values(1,'Samsung Galaxy S4',16,8,5.0,1871.10,2);
insert into CELULAR_INFO(ID_CELULAR_INFO,DS_MODELO,NR_MEMORIA,NR_CAMERA_TRASEIRA_MP,NR_TELA_TAMANHO,NR_PRECO) 
values(2,'Samsung Galaxy S6 Edge',32,27.7,5.1,2199.12 );
insert into CELULAR_INFO(ID_CELULAR_INFO,DS_MODELO,NR_MEMORIA,NR_CAMERA_TRASEIRA_MP,NR_TELA_TAMANHO,NR_PRECO,NR_CAMERA_FRONTAL_MP) 
values(3,'Sony Xperia Z3',32,20.7,5.2, 1599,5 );
insert into CELULAR_INFO(ID_CELULAR_INFO,DS_MODELO,NR_MEMORIA,NR_CAMERA_TRASEIRA_MP,NR_TELA_TAMANHO,NR_PRECO,NR_CAMERA_FRONTAL_MP) 
values(4,'iPhone 6',16,8,4.7, 3199.00,1.2 );
insert into CELULAR_INFO(ID_CELULAR_INFO,DS_MODELO,NR_MEMORIA,NR_CAMERA_TRASEIRA_MP,NR_TELA_TAMANHO,NR_PRECO,NR_CAMERA_FRONTAL_MP)
values(5,'Motorola Moto X Play Colors 32GB',32,21,5.5, 1301.52,5);
insert into CELULAR_INFO(ID_CELULAR_INFO,DS_MODELO,NR_MEMORIA,NR_CAMERA_TRASEIRA_MP,NR_TELA_TAMANHO,NR_PRECO,NR_CAMERA_FRONTAL_MP) 
values(6,'LG G4 Stylus HDTV 16 GB',16,13,5.7, 1028.72,5);
insert into CELULAR_INFO(ID_CELULAR_INFO,DS_MODELO,NR_MEMORIA,NR_CAMERA_TRASEIRA_MP,NR_TELA_TAMANHO,NR_PRECO,NR_CAMERA_FRONTAL_MP) 
values(7,'Nokia lumia 830',16,10,5, 1019,0.9);
insert into CELULAR_INFO(ID_CELULAR_INFO,DS_MODELO,NR_MEMORIA,NR_CAMERA_TRASEIRA_MP,NR_TELA_TAMANHO,NR_PRECO,NR_CAMERA_FRONTAL_MP) 
values(8,'iPhone 4',32,5,3.5, 1028.72,0.3);
insert into CELULAR_INFO(ID_CELULAR_INFO,DS_MODELO,NR_MEMORIA,NR_CAMERA_TRASEIRA_MP,NR_TELA_TAMANHO,NR_PRECO,NR_CAMERA_FRONTAL_MP) 
values(9,'Motorola Moto X Force',64,21,5.4, 2969,5);
insert into CELULAR_INFO(ID_CELULAR_INFO,DS_MODELO,NR_MEMORIA,NR_CAMERA_TRASEIRA_MP,NR_TELA_TAMANHO,NR_PRECO,NR_CAMERA_FRONTAL_MP) 
values(10,'Sony Xperia Z5',32,23,5.2, 3429,5);
